### ISSUE TITLE
exec: "solc and solcjs": executable 

### ISSUE THREAD

**Issue by cayden** [meshplus/gosdk#1]
当执行下面代码出现

   code, _ := common.ReadFileAsString("./conf/contract/Accumulator.sol")
	cr, stdErr := rpcAPI.CompileContract(code)
	if stdErr != nil {
		logger.Error(stdErr)
		return
	}

 Internal server error: exec: "solc and solcjs": executable file not found in $PATH

但是在本地是安装了solc 和solcjs的

**Comment by panos-xyz** [comment]
节点是在本地部署的还是在远程服务器部署的?
另外solc 或者solcjs 有没有配置在环境变量里面?

**Comment by cayden** [comment]
@yp945 hi,节点是在远程服务器部署的，用的docker环境
hyperchaincn/solo:v2.0.0，单节点。

**Comment by cayden** [comment]
在本机(mac) 也用docker pull 单节点，并且用java sdk  hvm测试成功，然后换成go sdk 出现如题错误。

**Comment by jiaohu** [comment]
检查节点的版本以及本地solc的版本, 核对[文档](https://github.com/meshplus/gosdk/blob/master/docs/hyperchain_gosdk_document.md)中4.1.5小节的报错信息
