### ISSUE TITLE
请问 RPC 是协程安全嘛

### ISSUE THREAD

**Issue by Alex-toughman** [meshplus/gosdk#2]
func NewRPCWithPath(confRootPath string) *RPC 
的返回值定义为全局变量，然后在并发的http响应中使用它

**Comment by jiaohu** [comment]
能具体举个例子(代码)吗，我不确认我想的跟你说的是不是一回事

**Comment by jiaohu** [comment]
> func NewRPCWithPath(confRootPath string) *RPC
> 的返回值定义为全局变量，然后在并发的http响应中使用它
