### ISSUE TITLE
flato节点如何开启websocket？

### ISSUE THREAD

**Issue by ljh-558** [meshplus/gosdk#20]
我需要利用sdk的wsCli.Subscribe(1, filter, listenerHandler{})监听链上合约触发的事件，但是官方给的免费版flato体验版教程没有给出如何开启websocket的方法。

**Comment by jiaohu** [comment]
你的体验版的版本号是多少？

**Comment by ljh-558** [comment]
我使用的下载文件名：hpc-flato-1.2.3-5-875e217-20221012-Ubuntu-16.04-试用版.tar.gz，版本号应该是1.2.3-5。

**Comment by jiaohu** [comment]
已经不支持websocket了

**Comment by ljh-558** [comment]
好的。是以后都不支持还是只是试用版不支持？
另有一个问题：我可以用sdk根据某个交易的hash获取到交易信息，但是交易信息里面并没有包含该交易的合约执行返回的结果，请问有其他方法可以获取一个交易对应的合约执行结果吗？

**Comment by jiaohu** [comment]
以后都不支持

**Comment by jiaohu** [comment]
没理解你说的第二个问题， TxReceipt里面的Ret不就是结果吗

**Comment by ljh-558** [comment]
TxReceipt里面的Ret是主动调用返回的结果。但是如果我利用刚才主动调用的交易hash作为参数调用GetTransactionByHash()，那么这个返回结果只有刚才我调用的交易信息，不包含合约执行结果。

**Comment by jiaohu** [comment]
emmm, 有拿reciept的接口呀， 可以看看wiki的文档

**Comment by ljh-558** [comment]
好的
